=== studentkittens/webarchive/test/xml/file.xsd
<?xml version="1.0"?>
<!--

-->

<xs:schema version="1.0"
		   xmlns:xs="http://www.w3.org/2001/XMLSchema"
		   xmlns="http://www.hof-university.de/webarchive"
		   targetNamespace="http://www.hof-university.de/webarchive"
  elementFormDefault="qualified"
  		   attributeFormDefault="qualified"

		
>
	<xs:element name="file">
		<xs:complexType>
			<xs:sequence>
				<xs:element name="meta">
					<xs:complexType>
						<xs:sequence>
							<xs:element name="commitTag">
								<xs:complexType>
									<xs:attribute name="commitTime" type="xs:dateTime" use="required" />
									<xs:attribute name="domain" type="xs:string" use="required" />
								</xs:complexType>
							</xs:element>
						</xs:sequence>

						<xs:attribute name="url" type="xs:anyURI" use="required"/>
						<xs:attribute name="mimeType" type="xs:string" use="required" />
						<xs:attribute name="path" type="xs:anyURI" use="required" />
						<xs:attribute name="createTime" type="xs:dateTime" use="required" />
						<xs:attribute name="title" type="xs:string" use="optional" />
					</xs:complexType>
				</xs:element>
				<xs:element name="data">
					<xs:complexType>
						<xs:sequence>
							<xs:element ref="dataElement"  minOccurs="0" maxOccurs="unbounded"/>
						</xs:sequence>
					</xs:complexType>
				</xs:element>
			</xs:sequence>
		</xs:complexType>
	</xs:element>

	<xs:element name="dataElement" abstract="true"/>
	
	<xs:element name="testData1" 
		substitutionGroup="dataElement"  
		>
		<xs:complexType>
			<xs:sequence>
				<xs:element name="content" type="xs:string"/>
			</xs:sequence>
		</xs:complexType>
	</xs:element>
	<xs:element name="testData2" 
		substitutionGroup="dataElement"  
		>
		<xs:complexType>
			<xs:sequence>
				<xs:element name="content" type="xs:string"/>
			</xs:sequence>
		</xs:complexType>
	</xs:element>
	
</xs:schema>

=== studentkittens/webarchive/test/xml/example.expected.xml
<?xml version="1.0" encoding="UTF-8"?>
<!--
To change this template, choose Tools | Templates
and open the template in the editor.
-->


<wa:file
	xmlns:xsi='http://www.w3.org/2001/XMLSchema-instance'
	xmlns:wa='http://www.hof-university.de/webarchive'
	xsi:schemaLocation='http://www.hof-university.de/webarchive file.xsd'>
	<wa:meta
		wa:url="www.heise.de/index.html"
		wa:mimeType="text/html"
		wa:path="www.heise.de/index.html"
		wa:createTime="2012-05-15T17:28:42"
		wa:title="heise online"
	>
		<wa:commitTag
			wa:commitTime="2012-05-15T17:30:00"
			wa:domain="www.heise.de"
		/>
	</wa:meta>
	<wa:data>
		<wa:testData1><wa:content>bla</wa:content></wa:testData1>
		<wa:testData2><wa:content>bla</wa:content></wa:testData2>
	</wa:data>
</wa:file>
